CREATE TABLE conta (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       data_vencimento DATE NOT NULL,
                       data_pagamento DATE,
                       valor NUMERIC(15, 2) NOT NULL,
                       descricao VARCHAR(255) NOT NULL,
                       situacao VARCHAR(50) NOT NULL
);